export const SOURCE_URL = "https://www.depts.ttu.edu/psy/about/labs.php";
export const BASE_COPIED = "2026-09-10";
const P = "https://www.depts.ttu.edu/psy/people/";

export const AREAS = ["Clinical", "Cognition & Cognitive Neuroscience", "Human Factors", "Social", "Counseling"];

// Copied from the TTU Psychological Sciences labs page. Research interests are summarized.
export const FACULTY = [
  { id: "ccummings", professor: "Dr. Caroline Cummings", title: "Assistant Professor", area: "Clinical",
    labName: "Pediatric Health, Affect, and Biobehavioral Lab", labUrl: "https://carolinedc515.wixsite.com/website",
    profileUrl: P + "ccummings/", email: "carolicu@ttu.edu",
    interests: "How emotions and related biobehavioral processes connect to health in the daily lives of youth and young adults who have, or are at risk for, chronic and complex medical conditions.",
    tags: ["pediatric health", "emotion", "chronic illness", "youth"] },
  { id: "alittlefield", professor: "Dr. Andrew Littlefield", title: "Professor; Admissions Coordinator", area: "Clinical",
    labName: "Substance Use Disorders Studies (SUDS) Lab", labUrl: "https://www.depts.ttu.edu/psy/SUDS/index.php",
    profileUrl: P + "alittlefield/", email: "Andrew.Littlefield@ttu.edu",
    interests: "How alcohol use changes across development and how it relates to personality, drinking motives, taking on adult roles, and genetic and environmental factors.",
    tags: ["alcohol use", "substance use", "personality", "development"] },
  { id: "brlancaster", professor: "Dr. Brittany Lancaster", title: "Assistant Professor", area: "Clinical",
    labName: "Health Outcomes, Promotion, & Evaluation (HOPE) Lab", labUrl: P + "brlancaster/index.php",
    profileUrl: P + "brlancaster/index.php", email: "brittany.lancaster@ttu.edu",
    interests: "Promoting health in children and teens, including sleep, obesity, mental health, and social media use, with a focus on social and environmental influences in rural and medically underserved communities.",
    tags: ["child health", "sleep", "social media", "rural health"] },
  { id: "smitchell", professor: "Dr. Sean Mitchell", title: "Associate Professor", area: "Clinical",
    labName: "Suicide Risk and Prevention Research (SRPR) Lab", labUrl: "https://www.drseanmmitchell.com/",
    profileUrl: P + "smitchell/", email: "sean.mitchell@ttu.edu",
    interests: "Suicide risk and prevention among people at high risk.",
    tags: ["suicide prevention", "risk"] },
  { id: "aschmidt", professor: "Dr. Adam Schmidt", title: "Associate Professor; Associate Chair", area: "Clinical",
    labName: "Pathways to Resilient Youth Development (PRYDE) Lab", labUrl: "https://www.depts.ttu.edu/psy/pryde/",
    profileUrl: P + "aschmidt/", email: "adam.t.schmidt@ttu.edu",
    interests: "How cognitive abilities, brain biology, and social environment interact to support positive development, especially among justice-involved youth and youth with traumatic brain injuries.",
    tags: ["youth development", "brain injury", "juvenile justice", "resilience"] },
  { id: "jsinger", professor: "Dr. Jonathan Singer", title: "Assistant Professor", area: "Clinical",
    labName: "Grief and Responses to Illness into Late Life (GRILL) Lab", labUrl: "https://jonathansinger3.wixsite.com/my-site",
    profileUrl: P + "jsinger/", email: "jonsinge@ttu.edu",
    interests: "Psychological health during aging and illness, and how biological, psychological, and social processes connect in people with life-limiting illnesses such as cancer or dementia, and in their caregivers.",
    tags: ["aging", "grief", "serious illness", "caregivers"] },
  { id: "jvanallen", professor: "Dr. Jason Van Allen", title: "Regents Professor; Director of Clinical Training", area: "Clinical",
    labName: "Examining Nutrition, Exercise, and Rest in Growing Youth (ENERGY) Lab", labUrl: P + "jvanallen/",
    profileUrl: P + "jvanallen/", email: "jason.vanallen@ttu.edu",
    interests: "Pediatric and health psychology, positive psychology, weight-management and physical activity interventions, and sleep medicine.",
    tags: ["pediatric psychology", "physical activity", "sleep", "positive psychology"] },
  { id: "svictor", professor: "Dr. Sarah Victor", title: "Associate Professor", area: "Clinical",
    labName: "Tracking Risk over Time Lab (TRTL)", labUrl: "https://www.sarahevictor.com/",
    profileUrl: P + "svictor/", email: "sarah.victor@ttu.edu",
    interests: "Non-suicidal self-injury and suicide: what raises risk across people, and what drives short-term changes in self-harm risk in daily life.",
    tags: ["self-injury", "suicide", "daily life research"] },

  { id: "pmarshall", professor: "Dr. Philip Marshall", title: "", area: "Cognition & Cognitive Neuroscience",
    labName: "Integrated Cognitive Studies Lab", labUrl: "https://www.depts.ttu.edu/psy/marshall-lab/",
    profileUrl: P + "pmarshall/", email: "",
    interests: "Human-animal interaction, especially how people process information about companion animals, along with longstanding interests in memory, motor skills, and aging.",
    tags: ["human-animal interaction", "pets", "memory", "aging"] },
  { id: "mscolari", professor: "Dr. Miranda Scolari", title: "", area: "Cognition & Cognitive Neuroscience",
    labName: "Selective Attention & Perception Lab", labUrl: P + "mscolari/",
    profileUrl: P + "mscolari/", email: "",
    interests: "What the human visual system can and can't do, and how attention recruits visual brain regions to help people reach their goals.",
    tags: ["attention", "vision", "perception", "neuroscience"] },
  { id: "rtaraban", professor: "Dr. Roman Taraban", title: "", area: "Cognition & Cognitive Neuroscience",
    labName: "Cognition Lab", labUrl: "https://www.depts.ttu.edu/psy/cognition/",
    profileUrl: P + "rtaraban/", email: "",
    interests: "Text analysis, early reading instruction, learning strategies, categorization, and engineering ethics.",
    tags: ["reading", "learning strategies", "categorization"] },
  { id: "ayoung", professor: "Dr. Alice Young", title: "", area: "Cognition & Cognitive Neuroscience",
    labName: "", labUrl: "", profileUrl: P + "ayoung/", email: "",
    interests: "Psychopharmacology: how drugs act as cues and rewards, and the receptor processes involved in developing drug tolerance and dependence.",
    tags: ["psychopharmacology", "drug dependence"] },
  { id: "swang", professor: "Dr. Sisi Wang", title: "", area: "Cognition & Cognitive Neuroscience",
    labName: "", labUrl: "", profileUrl: P + "swang/index.php", email: "",
    interests: "How visual attention, working memory, long-term memory, and action planning interact; the brain mechanisms of working memory and ways to enhance it; statistical learning; and links between emotion, attention, and memory.",
    tags: ["working memory", "attention", "emotion", "neuroscience"] },

  { id: "hchoi", professor: "Dr. HeeSun Choi", title: "", area: "Human Factors",
    labName: "", labUrl: "", profileUrl: P + "hchoi/", email: "",
    interests: "Workplace and driving safety related to attention and age-related decline, safety in human-robot interaction, and virtual reality and simulation technology.",
    tags: ["driving safety", "robots", "virtual reality", "aging"] },
  { id: "egreenlee", professor: "Dr. Eric Greenlee", title: "", area: "Human Factors",
    labName: "", labUrl: "", profileUrl: P + "egreenlee/", email: "",
    interests: "Brain and body measures of workload, fatigue, and vigilance; how people interact with automation such as self-driving cars; and workload in individuals and teams.",
    tags: ["fatigue", "automation", "self-driving cars", "workload"] },
  { id: "kjones", professor: "Dr. Keith Jones", title: "", area: "Human Factors",
    labName: "", labUrl: "", profileUrl: P + "kjones/", email: "",
    interests: "Human-computer and human-robot interaction, human factors in cybersecurity, and affordance perception.",
    tags: ["human-computer interaction", "robots", "cybersecurity"] },
  { id: "mramasubramanian", professor: "Dr. Madhuri Ramasubramanian", title: "", area: "Human Factors",
    labName: "", labUrl: "", profileUrl: P + "mramasubramanian/index.php", email: "",
    interests: "How people perceive and understand risk, and how that shapes their judgments and decisions.",
    tags: ["risk perception", "decision-making"] },
  { id: "braveendranath", professor: "Dr. Bala Raveendranath", title: "", area: "Human Factors",
    labName: "", labUrl: "", profileUrl: P + "braveendranath/", email: "",
    interests: "Perception and motor control in real, augmented, and virtual environments.",
    tags: ["perception", "motor control", "virtual reality"] },

  { id: "jalquist", professor: "Dr. Jessica Alquist", title: "", area: "Social",
    labName: "Alquist Lab", labUrl: "https://www.depts.ttu.edu/psy/alquistlab/",
    profileUrl: P + "jalquist/", email: "",
    interests: "Self-control and its effects on physical health, sense of agency, uncertainty, emotion, and how belief in free will influences behavior.",
    tags: ["self-control", "free will", "emotion", "health"] },
  { id: "ajung", professor: "Dr. Annie Jung", title: "", area: "Social",
    labName: "", labUrl: "https://ahsjung.com", profileUrl: "", email: "",
    interests: "The social-psychological factors that help or hurt cooperation between individuals and groups.",
    tags: ["cooperation", "groups"] },
  { id: "atalley", professor: "Dr. Amelia Talley", title: "", area: "Social",
    labName: "Stigma, Health, and Applied Research Center (SHARC)", labUrl: "https://www.depts.ttu.edu/psy/sharc/",
    profileUrl: P + "atalley/", email: "",
    interests: "How people function personally and socially under stress, sexual identity, and psychological and physical health when facing stigma and threats to self-concept.",
    tags: ["stigma", "sexual identity", "stress", "health"] },
  { id: "xshen", professor: "Dr. Xi Shen", title: "", area: "Social",
    labName: "Lab coming soon", labUrl: "", profileUrl: P + "xshen/", email: "",
    interests: "Person perception, attitudes, and behavior, studied with a social cognitive approach.",
    tags: ["person perception", "attitudes", "social cognition"] },

  { id: "sgaros", professor: "Dr. Sheila Garos", title: "", area: "Counseling",
    labName: "", labUrl: "https://s3xlab.wixsite.com/research", profileUrl: P + "sgaros/", email: "",
    interests: "Human sexual behavior, behavioral addictions, sexual temptation bias, women's OB/GYN health, and women's objectification of other women.",
    tags: ["sexuality", "behavioral addictions", "women's health"] },
  { id: "pingram", professor: "Dr. Paul B. Ingram", title: "", area: "Counseling",
    labName: "", labUrl: "", profileUrl: P + "pingram/", email: "",
    interests: "Personality measurement, issues facing veterans such as PTSD and traumatic brain injury, and mental health stigma as it relates to attitudes, treatment, and physical health.",
    tags: ["veterans", "PTSD", "personality assessment", "stigma"] },
  { id: "hkim", professor: "Dr. Haram Kim", title: "", area: "Counseling",
    labName: "", labUrl: "", profileUrl: P + "hkim/", email: "",
    interests: "How work and well-being intersect, work among marginalized groups, structural inequality at work, the school-to-work transition, and career interventions.",
    tags: ["careers", "well-being", "inequality"] },
  { id: "bpina-watson", professor: "Dr. Brandy Piña-Watson", title: "", area: "Counseling",
    labName: "Latinx Mental Health & Resilience Lab", labUrl: "https://brandypinawatson.wixsite.com/lmhrl",
    profileUrl: P + "bpina-watson/", email: "",
    interests: "Mental health disparities among Latinx teens and young adults, especially those of Mexican descent: how individual, family, cultural, and societal factors affect depression, suicidal thoughts, well-being, and school outcomes, plus gender socialization and prevention programs.",
    tags: ["Latinx mental health", "depression", "culture", "adolescents"] },
  { id: "crobitschek", professor: "Dr. Christine Robitschek", title: "", area: "Counseling",
    labName: "", labUrl: "", profileUrl: P + "crobitschek/", email: "",
    interests: "Positive psychology, multicultural aspects of personal growth initiative, and what personal growth initiative means for health, illness, and interventions.",
    tags: ["positive psychology", "personal growth", "culture"] },
  { id: "cwarlick", professor: "Dr. Craig Warlick", title: "", area: "Counseling",
    labName: "", labUrl: "", profileUrl: P + "cwarlick/", email: "",
    interests: "What shapes mental health treatment: how evidence-based treatments are delivered, training for mental health professionals, religion's links with mental health and work, and better measurement, with an emphasis on health disparities and equitable access.",
    tags: ["mental health treatment", "religion", "health equity"] },
];
